FATCA Data Preparation and Transmission System/Models/NotificationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FATCA_Data_Preparation_and_Transmission_System.Models
{
    public class NotificationsViewModel
    {
        public HttpPostedFileBase EncryptedNotification { get; set; }
        public HttpPostedFileBase SenderCertificate { get; set; }
        public string SenderCertPassword { get; set; }
    }
}

FATCA Data Preparation and Transmission System/Controllers/EncryptController.cs
using FATCA_Data_Preparation_and_Transmission_System.Models;
using System;
using System.Web.Mvc;
using System.IO;
using FATCA_Data_Preparation_and_Transmission_System.Helpers;
using System.Net;

namespace FATCA_Data_Preparation_and_Transmission_System.Controllers
{
    public class EncryptController : Controller
    {
        // GET: Encrypt
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(EncryptViewModel encryption)
        {
            if (ModelState.IsValid)
            {
                // Paths for each file that we are going to store on disk
                string mainDirectory = Server.MapPath("~/App_Data/Encrypt/");
                string certificatesDirectory = Server.MapPath("~/App_Data/Certificates/");
                string subDir = DateTime.UtcNow.ToString("yyyyMMddTHHmmssfff") + "\\";
                string encryptedDirectory = Path.Combine(mainDirectory, subDir);

                string xmlReportPath = Path.Combine(encryptedDirectory, encryption.Report.FileName);
                string senderCertificatePath = Path.Combine(certificatesDirectory, "sender.pfx");
                string receiverCertificatePath = Path.Combine(certificatesDirectory, "receiver.cer");
                string hctaCertificatePath = ""; // Optional

                // Create subdirectory
                Directory.CreateDirectory(encryptedDirectory);

                // Save xml report to the disk
                encryption.Report.SaveAs(xmlReportPath);

                // Read certificates
                byte[] senderCertificate;
                using (Stream inputStream = encryption.SenderCertificate.InputStream)
                {
                    MemoryStream memoryStream = inputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        inputStream.CopyTo(memoryStream);
                    }
                    senderCertificate = memoryStream.ToArray();
                }

                byte[] irsCertificate;
                using (Stream inputStream = encryption.IRSCertificate.InputStream)
                {
                    MemoryStream memoryStream = inputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        inputStream.CopyTo(memoryStream);
                    }
                    irsCertificate = memoryStream.ToArray();
                }

                byte[] hctaCertificate = { };
                if (encryption.Model1Option2)
                {
                    using (Stream inputStream = encryption.HCTACertificate.InputStream)
                    {
                        MemoryStream memoryStream = inputStream as MemoryStream;
                        if (memoryStream == null)
                        {
                            memoryStream = new MemoryStream();
                            inputStream.CopyTo(memoryStream);
                        }
                        hctaCertificate = memoryStream.ToArray();
                    }
                }

                // Perform the schema validation
                //string validationError = XmlManager.CheckSchema(xmlReportPath, "Schemas folder");

                //if (validationError != "")
                //{
                //   return Json(new { StatusCode = HttpStatusCode.InternalServerError, errorMessage = "Schema validation error: " + validationError });
                //}

                // Load XML report content
                byte[] xmlContent = System.IO.File.ReadAllBytes(xmlReportPath);
                string senderGIIN = Path.GetFileNameWithoutExtension(encryption.Report.FileName);
                string fileExtension = Path.GetExtension(encryption.Report.FileName.ToUpper()).Replace(".", "");

                // Perform signature
                byte[] signedReport = XmlManager.Sign(XmlSignatureType.Enveloping, xmlContent, senderCertificate, encryption.SenderCertPassword, xmlReportPath);
                string signedReportPath = xmlReportPath.Replace(".xml", "_Payload.xml");

                string zipPackagePath = signedReportPath.Replace(".xml", ".zip");

                // Save signed xml report to the disk
                System.IO.File.WriteAllBytes(signedReportPath, signedReport);

                // Create the zip archive that will hold the generated files, and add the signed report to it
                ZipManager.CreateArchive(signedReportPath, zipPackagePath);

                // Generate AES key (32 bytes) & default initialization vector (empty)
                byte[] aesEncryptionKey = AesManager.GenerateRandomKey(AesManager.KeySize / 8);
                byte[] aesEncryptionVector = AesManager.GenerateRandomKey(16, false);

                // Encrypt file and save to disk
                string encryptedFilePath = zipPackagePath.Replace(".zip", "");
                string encryptedHCTAFilePath = zipPackagePath.Replace(".zip", "");
                string payloadFilePath = encryptedFilePath + "";
                AesManager.EncryptFile(zipPackagePath, encryptedFilePath, aesEncryptionKey, aesEncryptionVector, false);

                // Encrypt AES key with the public key of the certificate and save to disk
                encryptedFilePath = Path.GetDirectoryName(zipPackagePath) + "\\000000.00000.TA.840_Key";
                AesManager.EncryptAesKey(aesEncryptionKey, aesEncryptionVector, irsCertificate, "yourpasswordhere", encryptedFilePath, false);

                //For Model1 Option2 Only, encrypt the AES Key with the HCTA Public Key
                if (encryption.Model1Option2)
                {
                    encryptedHCTAFilePath = Path.GetDirectoryName(zipPackagePath) + "\\000000.00000.TA." + "901" + "_Key";
                    AesManager.EncryptAesKey(aesEncryptionKey, aesEncryptionVector, hctaCertificate, "", encryptedHCTAFilePath, false);
                }

                // cleanup
                signedReport = null;
                aesEncryptionKey = aesEncryptionVector = null;

                string packageName = "";
                try
                {
                    DateTime uDat = new DateTime();
                    uDat = DateTime.UtcNow;
                    packageName = uDat.ToString("yyyyMMddTHHmmssfffZ") + "_" + senderGIIN;
                    string metadataFilePath = Path.Combine(encryptedDirectory, senderGIIN + "_Metadata.xml");
                    XmlManager.CreateMetadataFile(metadataFilePath, fileExtension, true, "2018", senderGIIN, packageName);
                    
                    // Check the signature to make sure it is valid, this requires the KeyInfo to be present
                    bool result = XmlManager.CheckSignature(signedReportPath);
                    if (result == false)
                    {
                        return Json(new { statusCode = HttpStatusCode.InternalServerError, errorMessage = "The document signature is not valid!" });
                    }

                    //Add the metadata, payload, and key files to the final zip package
                    // Add signed file to the zip package
                    ZipManager.CreateArchive(metadataFilePath, encryptedDirectory + "\\" + packageName + ".zip");
                    ZipManager.UpdateArchive(encryptedFilePath, encryptedDirectory + "\\" + packageName + ".zip");
                    ZipManager.UpdateArchive(payloadFilePath, encryptedDirectory + "\\" + packageName + ".zip");
                    
                    //Add the HCTA Key file for a Model 1 Option 2 packet
                    if (encryption.Model1Option2)
                    {
                        ZipManager.UpdateArchive(encryptedHCTAFilePath, encryptedDirectory + "\\" + packageName + ".zip");
                    }
                }
                catch (Exception e)
                {
                    throw e;
                }

                encryption.PackagePath = encryptedDirectory + "\\" + packageName + ".zip";

                return RedirectToAction("Download", new { packagePath = encryptedDirectory + "\\" + packageName + ".zip" });
            } else
            {
                return View(encryption);
            }
        }

        public ActionResult Download(string packagePath)
        {
            ViewBag.PackagePath = packagePath;
            return View();
        }

        public FileStreamResult DownloadPackage(string packagePath)
        {
            string packageName = Path.GetFileName(packagePath);
            FileStream fileStream = new FileStream(packagePath, FileMode.Open, FileAccess.Read, FileShare.None, 4096);
            return File(fileStream, System.Net.Mime.MediaTypeNames.Application.Octet, packageName);
        }

    }
}

FATCA Data Preparation and Transmission System/Controllers/NotificationsController.cs
using FATCA_Data_Preparation_and_Transmission_System.Helpers;
using FATCA_Data_Preparation_and_Transmission_System.Models;
using System;
using System.IO;
using System.Web.Mvc;

namespace FATCA_Data_Preparation_and_Transmission_System.Controllers
{
    public class NotificationsController : Controller
    {
        // GET: Notifications
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Decrypt(NotificationsViewModel notification)
        {
            if (ModelState.IsValid)
            {
                // Paths for each file that we are going to store on disk
                string mainDirectory = Server.MapPath("~/App_Data/Decrypt/");
                string certificatesDirectory = Server.MapPath("~/App_Data/Certificates/");
                string subDir = DateTime.UtcNow.ToString("yyyyMMddTHHmmssfff") + "\\";
                string decryptedDirectory = Path.Combine(mainDirectory, subDir);
                string encryptedNotificationPath = Path.Combine(decryptedDirectory, notification.EncryptedNotification.FileName);
                string senderCertificatePath = Path.Combine(certificatesDirectory, "sender.pfx");

                //Create subdirectory
                Directory.CreateDirectory(decryptedDirectory);

                // Save the files to disk
                notification.EncryptedNotification.SaveAs(encryptedNotificationPath);

                // Read certificate
                byte[] senderCertificate;
                using (Stream inputStream = notification.SenderCertificate.InputStream)
                {
                    MemoryStream memoryStream = inputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        inputStream.CopyTo(memoryStream);
                    }
                    senderCertificate = memoryStream.ToArray();
                }

                string zipFolder = "";
                try
                {
                    //Deflate the zip archive
                    zipFolder = ZipManager.ExtractArchive(encryptedNotificationPath, decryptedDirectory);
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("~/Views/Shared/Info.cshtml");
                }

                //Decrypt the Payload
                string decryptedNotificationPath = "";
                try
                {
                    decryptedNotificationPath = AesManager.DecryptNotification(zipFolder, senderCertificate, notification.SenderCertPassword, false);
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("~/Views/Shared/Info.cshtml");
                }

                ViewBag.DecryptedNotificationPath = decryptedNotificationPath;
                ViewBag.DecryptedNotificationXML = System.IO.File.ReadAllText(decryptedNotificationPath);
                return View("~/Views/Notifications/Download.cshtml");
            }
            else
            {
                return View(notification);
            }
        }
    }
}

FATCA Data Preparation and Transmission System/Controllers/SendController.cs
using FATCA_Data_Preparation_and_Transmission_System.Models;
using System;
using System.Web.Mvc;
using System.IO;
using WinSCP;
using FATCA_Data_Preparation_and_Transmission_System.Helpers;

namespace FATCA_Data_Preparation_and_Transmission_System.Controllers
{
    public class SendController : Controller
    {
        // GET: Send
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string packagePath)
        {
            ViewBag.PackagePath = packagePath;
            return View();
        }

        public ActionResult Send(SendViewModel sendView, string packagePath)
        {
            if (!string.IsNullOrEmpty(sendView.PackagePath))
            {
                ModelState["EncryptedPackage"].Errors.Clear();
                if (ModelState.IsValid)
                {
                    // Setup sessions options
                    SessionOptions currentSFTPSession = SFTPManager.CreateSFTPSession(sendView.SFTPServer, sendView.SFTPUsername, sendView.SFTPPassword);
                    string sftpUpName = packagePath;

                    try
                    {
                        string transferResult = SFTPManager.UploadFile(currentSFTPSession, sftpUpName);
                        ViewBag.Message = transferResult;
                    } 
                    catch (Exception e)
                    {
                        ViewBag.Message = e.Message;
                    }

                    return View("~/Views/Shared/Info.cshtml");
                }
                else
                {
                    return View(sendView);
                }
            }
            else
            {
                // File got uploaded from the user
                ModelState["PackagePath"].Errors.Clear();
                if (ModelState.IsValid)
                {
                    string dir = Server.MapPath("~/App_Data/Send/");
                    string tempPackagePath = Path.Combine(dir, sendView.EncryptedPackage.FileName);

                    // Save xml report to the disk
                    sendView.EncryptedPackage.SaveAs(tempPackagePath);

                    // Setup sessions options
                    SessionOptions currentSFTPSession = SFTPManager.CreateSFTPSession(sendView.SFTPServer, sendView.SFTPUsername, sendView.SFTPPassword);
                    string sftpUpName = tempPackagePath;

                    try
                    {
                        string transferResult = SFTPManager.UploadFile(currentSFTPSession, sftpUpName);
                        ViewBag.Message = transferResult;
                    }
                    catch (Exception e)
                    {
                        ViewBag.Message = e.Message;
                    }

                    return View("~/Views/Shared/Info.cshtml");
                }
                else
                {
                    return View(sendView);
                }
            }
        }
    }
}

FATCA Data Preparation and Transmission System/Views/Notifications/Download.cshtml
@model FATCA_Data_Preparation_and_Transmission_System.Models.NotificationsViewModel
@{
    ViewBag.Title = "Download";
    var decryptedNotificationXml = ViewBag.DecryptedNotificationXML;
    var decryptedNotificationPath = ViewBag.DecryptedNotificationPath;
    var decryptedNotificationName = Path.GetFileName(ViewBag.DecryptedNotificationPath);
}
<br />
<br />
<div class="card rounded-0 shadow col-lg-8 offset-lg-2">
    <div class="card-header bg-white"><h2 class="m-0">Decrypted notification</h2></div>
    <div class="card-body">
        <p>Notification <b>@Html.DisplayFor(m => decryptedNotificationName)</b></p>

        @using (Html.BeginForm("Index", "Send", new { packagePath = ViewBag.PackagePath }, FormMethod.Post, new { enctype = "multipart/form-data", @class = "text-center" }))
        {

            <button id="btnRead" class="btn btn-md btn-primary col-md-5 offset-md-3 m-0"><i class="fa fa-file-code-o" aria-hidden="true"></i> Read notification</button>
        }

        @using (Html.BeginForm("DownloadPackage", "Encrypt", new { packagePath = decryptedNotificationPath }, FormMethod.Post, new { enctype = "multipart/form-data", @class = "text-center" }))
        {
            <button type="submit" class="btn btn-md btn-primary col-md-5 offset-md-3 m-0 mt-3">
                <i class="fa fa-cloud-download" aria-hidden="true"></i> Download
            </button>
        }

    </div>
</div>

<script>

    $("#btnRead").click(function (e) {
        e.preventDefault();
        let notification = unescape(@Html.Raw(Json.Encode(decryptedNotificationXml)));
        $(".modal-body").append('<ul id="treeView"><li></li></ul>');
        $('#treeView').show();
        $(".modal").modal("show");

        var tree = $.parseXML(notification);

        traverse($('#treeView li'), tree.firstChild);
        $('<b style="color: #234e76; cursor: pointer; font-size: 20px">–<\/b>')
            .prependTo('#treeView li:has(li)')
            .click(function () {
                var sign = $(this).text();
                if (sign === "–")
                    $(this).text('+').next().children().hide();
                else
                    $(this).text('–').next().children().show();
            });
    });

    function readNotification(e) {
        e.preventDefault();
        let notification = '@Html.Raw(Json.Encode(decryptedNotificationXml))';
        $(".modal-body").append('<ul id="treeView"><li></li></ul>');
        $('#treeView').show();
        $(".modal").modal("show");

        var tree = $.parseXML(notification);

        traverse($('#treeView li'), tree.firstChild);
        $('<b style="color: rgb(121, 106, 238); cursor: pointer; font-size: 20px">–<\/b>')
            .prependTo('#treeView li:has(li)')
            .click(function () {
                var sign = $(this).text();
                if (sign === "–")
                    $(this).text('+').next().children().hide();
                else
                    $(this).text('–').next().children().show();
            });
    }

    function traverse(node, tree) {
        var children = $(tree).children();
        node.append(tree.nodeName);
        if (children.length) {
            var ul = $("<ul>").appendTo(node);
            children.each(function () {
                var li = $('<li>').appendTo(ul);
                traverse(li, this);
            });
        } else {
            $('<ul><li><strong>' + $(tree).text() + '</strong><\/li><\/ul>').appendTo(node);
        }
    }

    fileLabelsEventHandlers();

    function fileLabelsEventHandlers() {
        $("input[type='file']").each(function() {
            $(this).change(function () {
                let filePath = $(this).prop("value");
                let fileName = filePath.substr(filePath.lastIndexOf("\\") + 1);

                console.log(fileName);

                if (fileName === "") {
                    //fileName = "No file chosen";
                }

                $(".input-group-addon[for='" + $(this).prop("name") + "'] + input").val(fileName);
            });
        });
    }

    function test() {
        console.log("The script is running...");
        var x = $("input[type='file']")[0];
        console.log("filel: " + x.value);
    }

    model1Option2();

    function model1Option2() {
        $("#Model1Option2").change(function () {
            if ($(this).prop("checked"))
                $(".model1Option2").css("display", "flex");
            else
                $(".model1Option2").css("display", "none");
        });
    }

</script>

FATCA Data Preparation and Transmission System/Views/Notifications/Index.cshtml
@model FATCA_Data_Preparation_and_Transmission_System.Models.NotificationsViewModel
@{
    ViewBag.Title = "Index";
}
<br />
<br />
<div class="card rounded-0 shadow col-lg-8 offset-lg-2">
    <div class="card-header bg-white"><h2 class="m-0">Decrypt notification</h2></div>
    <div class="card-body">

        @using (Html.BeginForm("Decrypt", "Notifications", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            @Html.AntiForgeryToken()

            <div class="row">
                @Html.Label("Encrypted notification", new { @class = "col-form-label col-sm-5" })
                <div class="col col-sm-7">
                    <div class="input-group">
                        <label class="input-group-addon" for="EncryptedNotification">
                            <i class="fa fa-file fileIcons"></i>
                        </label>
                        <input readonly type="text" placeholder="No file chosen" class="form-control">
                    </div>
                    @Html.TextBox("EncryptedNotification", null, new { @class = "form-control d-none", type = "file" })
                    @Html.ValidationMessageFor(m => m.EncryptedNotification)
                </div>
            </div>

            <div class="row">
                @Html.Label("Sender private key", new { @class = "col-form-label col-sm-5" })
                <div class="col col-sm-7">
                    <div class="input-group">
                        <label class="input-group-addon" for="SenderCertificate">
                            <i class="fa fa-file fileIcons"></i>
                        </label>
                        <input readonly type="text" placeholder="No file chosen" class="form-control">
                    </div>
                    @Html.TextBox("SenderCertificate", null, new { @class = "form-control d-none", type = "file" })
                    @Html.ValidationMessageFor(m => m.SenderCertificate)

                </div>
            </div>

            <div class="row mb-4">
                @Html.Label("Sender private key password", new { @class = "col-form-label col-sm-5" })
                <div class="col col-sm-7">
                    <div class="input-group">
                        <div class="input-group-addon invisible d-none">
                            <i class="fa fa-file fileIcons"></i>
                        </div>
                        @Html.TextBox("SenderCertPassword", null, new { @class = "form-control", type = "password", placeholder = "Password" })
                    </div>
                </div>
            </div>

            

            <div class="form-group row">
                <div class="col-lg-10"></div>
                <div class="col col-lg-2 text-right">
                    <button type="submit" class="btn btn-primary m-0">Decrypt</button>
                </div>
            </div>

        }

    </div>
</div>

<script>

    fileLabelsEventHandlers();

    function fileLabelsEventHandlers() {
        $("input[type='file']").each(function() {
            $(this).change(function () {
                let filePath = $(this).prop("value");
                let fileName = filePath.substr(filePath.lastIndexOf("\\") + 1);

                console.log(fileName);

                if (fileName === "") {
                    //fileName = "No file chosen";
                }

                $(".input-group-addon[for='" + $(this).prop("name") + "'] + input").val(fileName);
            });
        });
    }

    function test() {
        console.log("The script is running...");
        var x = $("input[type='file']")[0];
        console.log("filel: " + x.value);
    }

    model1Option2();

    function model1Option2() {
        $("#Model1Option2").change(function () {
            $(".model1Option2").toggleClass("d-none");
        });
    }

</script>